/* Settings component section; state is created for each CRM instance. */
window.ZenSettings = window.ZenSettings || {};
window.ZenSettings.state = function () { return {
        permissionCatalog: [],
        managedRoles: [],
        roleRules: {},
        teamRules: {},
        permissionSubject: 'role:manager',
        permissionError: '',
        permissionSaved: '',
        newRoleName: '',
        roleNameDraft: '',
        effectivePermissions: {},
        menuModulesList: [
            { id: 'dashboard', label: 'Dashboard', group: 'Główne' },
            { id: 'clients', label: 'CRM - Klienci', group: 'CRM' },
            { id: 'leads', label: 'CRM - Leady', group: 'CRM' },
            { id: 'contacts', label: 'CRM - Kontakty', group: 'CRM' },
            { id: 'projects', label: 'Projekty', group: 'Główne' },
            { id: 'tasks', label: 'Zadania', group: 'Główne' },
            { id: 'meetings', label: 'Kalendarz', group: 'Główne' },
            { id: 'services', label: 'Usługi', group: 'Usługi' },
            { id: 'serviceCatalog', label: 'Katalog usług', group: 'Usługi' },
            { id: 'offers', label: 'Oferty', group: 'Dokumenty' },
            { id: 'documents', label: 'Dokumenty', group: 'Dokumenty' },
            { id: 'templates', label: 'Szablony', group: 'Dokumenty' },
            { id: 'tickets', label: 'Lista ticketów', group: 'Tickety' },
            { id: 'ticketSettings', label: 'Ustawienia ticketów', group: 'Tickety' },
            { id: 'sms', label: 'Telefonia & SMS', group: 'Komunikacja' },
            { id: 'archive', label: 'Archiwum', group: 'System' },
        ],
        menuPermissionsState: {},
        savingMenuSettings: false,
        menuSettingsSaved: false,

        leadSources: ['Strona WWW', 'Polecenie', 'Telefon', 'Social Media', 'Kampania Google', 'Inne'],
        newLeadSourceName: '',
        editingLeadSourceIndex: null,
        editingLeadSourceName: '',
        leadWebhookEnabled: false,
        leadWebhookToken: '',
        savingLeadSettings: false,
        leadSettingsSaved: false,
}; };
