const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const sandbox = {localStorage: {getItem: () => null}, window: {ZenI18n: {t: text => text}}};
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync('frontend/js/modules/records.js', 'utf8'), sandbox);
(async () => {
    const app = sandbox.window.ZenModules.records();
    app.settingsForm = {gus_enabled: 'true'};
    app.modal = {open: true, form: {nip: '526-104-08-28', krs: '0000123456'}};
    app.api = async path => {
        assert.equal(path, '/clients/company-lookup?nip=5261040828');
        return {company: 'GUS', nip: '5261040828', regon: '000331501', city: 'Warszawa'};
    };
    app.settingsForm.gus_enabled = 'false';
    await app.lookupClientGus();
    assert.equal(app.modal.form.company, undefined);
    app.settingsForm.gus_enabled = 'true';
    await app.lookupClientGus();
    assert.equal(app.modal.form.name, 'GUS');
    assert.equal(app.modal.form.city, 'Warszawa');
    assert.equal(app.modal.form.krs, '0000123456');
    assert.equal(app.gusLookup.loading, false);
    app.settingsForm.client_company_provider = 'mf';
    assert.equal(app.gusSearchEnabled, true);
    app.settingsForm.client_statuses = JSON.stringify([{id: 'vip', label: 'VIP', accent: '#123456'}]);
    assert.equal(app.clientStatusLabel('vip'), 'VIP');
    assert.equal(app.clientStatusStyle('vip').color, '#123456');
    app.settingsForm.client_company_provider = 'off';
    assert.equal(app.gusSearchEnabled, false);
    app.settingsForm.client_company_provider = 'gus';
    app.clients = [{status: 'vip', assignee_id: 1}, {status: 'vip'}, {status: 'other'}];
    app.settingsForm.client_metrics = JSON.stringify([{id: 'all', color: '#ffffff'}, {id: 'status:vip', color: '#123456'}]);
    assert.equal(app.clientMetrics.length, 2);
    assert.equal(app.clientMetricCount('status:vip'), 2);
    assert.equal(app.clientMetricCount('assigned'), 1);
    assert.equal(app.clientMetricStyle(app.clientMetrics[0])['--client-metric-text'], '#14283d');
    app.settingsForm.client_metrics = '[]';
    assert.equal(app.clientMetrics.length, 0);
    app.modal.form.nip = '12';
    await app.lookupClientGus();
    assert.ok(app.gusLookup.error);
    app.modal.form.nip = '5261040828';
    app.api = async () => {app.modal.form = {name: 'Inny klient'}; return {company: 'GUS'};};
    await app.lookupClientGus();
    assert.equal(app.modal.form.name, 'Inny klient');
    console.log('Client GUS frontend tests passed');
})().catch(error => {console.error(error); process.exitCode = 1;});
