const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const store = new Map();
const sandbox = {window:{},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v))},location:{hash:''},Date,console,setTimeout,clearTimeout};
vm.createContext(sandbox);
for(const name of ['../locales/pl','../locales/en','i18n','config','ux',...fs.readdirSync('frontend/js/modules').filter(n=>n.endsWith('.js')).map(n=>'modules/'+n.slice(0,-3)),'app']) vm.runInContext(fs.readFileSync(`frontend/js/${name}.js`,'utf8'),sandbox);
const app = sandbox.crmApp();
const portalMenu = app.menu.find(item => item.id === 'portal_group');
assert.ok(portalMenu.children.some(item => item.id === 'portalTickets'));
assert.ok(portalMenu.children.some(item => item.id === 'portalSpaces'));
const ticketsMenu = app.menu.find(item => item.id === 'tickets_group');
assert.ok(ticketsMenu);
assert.ok(ticketsMenu.children.some(item => item.id === 'tickets'));
assert.ok(ticketsMenu.children.some(item => item.id === 'ticketSettings'));
app.tickets = [{ id: 1, ticket_number: 'TCK-001', title: 'Problem', status: 'new', category: 'technical', priority: 'high' }];
assert.equal(app.ticketStats.new, 1);
assert.equal(app.ticketStatusLabel('new'), 'Nowy');
// Local-midnight dates must not move to the previous UTC day.
const date = new Date(2026,8,27,0,15);
assert.equal(app.localDateKey(date),'2026-09-27');
app.meetings=[{id:1,title:'Meeting',start_time:'2026-09-27T00:15:00'}];
app.tasks=[{id:2,title:'Task',due_date:'2026-09-27T12:00:00'}];
assert.equal(app.calendarEventsFor({date}).length,2);
const items=Array.from({length:55},(_,id)=>({id}));
assert.equal(app.pagedItems('clients',items).length,10);
app.setListPage('clients',3,items.length);
assert.equal(app.pagedItems('clients',items)[0].id,20);
app.setListPageSize('clients',20);
assert.equal(app.pagedItems('clients',items).length,20);
assert.equal(app.listPage('clients',5),1);
app.setListPage('clients',3,items.length);
assert.equal(app.listPage('clients',5),1);
assert.equal(app.pagedItems('clients',items.slice(0,5)).length,5);
app.calendarMode='tasks';assert.equal(app.calendarEventsFor({date})[0].title,'Task');
app.calendarMode='meetings';assert.equal(app.calendarEventsFor({date})[0].title,'Meeting');
app.customLeadStages=[{id:'review',label:'Weryfikacja',accent:'#007fce'}];
assert.equal(app.fieldsFor('leads').find(f=>f.key==='stage').options[0].label,'Weryfikacja');
app.editTaskStages();
app.addTaskStage();
assert.equal(app.taskStageDraft.length,4);
assert.equal(app.taskStageDraft[2].label,'Nowy status');
const extraTaskStage=app.taskStageDraft[2];
app.taskStatusStages=app.taskStageDraft.map(stage=>({...stage}));
assert.ok(app.fieldsFor('tasks').find(f=>f.key==='status').options.some(option=>option.value===extraTaskStage.id));
app.tasks=[{id:2,title:'Task',status:extraTaskStage.id}];
assert.ok(app.taskBoardStages.some(stage=>stage.id===extraTaskStage.id));
app.removeTaskStage(extraTaskStage.id);
assert.equal(app.taskStageDraft.length,3);
app.taskStatusStages=app.taskStageDraft.map(stage=>({...stage}));
const contextApp=sandbox.crmApp();
contextApp.ensureLookups=()=>{};
contextApp.loadCustomFields=()=>{};
contextApp.currentView='clients';
contextApp.detailView={type:'client',id:42,data:{}};
contextApp.quickAdd('task');
assert.equal(contextApp.modal.form.client_id,42);
assert.equal(contextApp.fieldsFor('tasks').some(f=>f.key==='client_id'||f.key==='lead_id'),false);
contextApp.detailView={type:'lead',id:17,data:{client_id:42}};
contextApp.quickAdd('document');
assert.equal(contextApp.modal.form.lead_id,17);
assert.equal(contextApp.fieldsFor('documents').some(f=>f.key==='client_id'||f.key==='lead_id'),false);
contextApp.quickAdd('meeting');
assert.equal(contextApp.modal.form.client_id,42);
assert.equal(contextApp.modal.form.lead_id,17);
contextApp.detailView={type:'lead',id:18,data:{}};
contextApp.quickAdd('meeting');
assert.equal(contextApp.modal.form.client_id,null);
assert.equal(contextApp.modal.form.lead_id,18);
assert.equal(contextApp.fieldsFor('meetings').some(f=>f.key==='client_id'||f.key==='lead_id'),false);
contextApp.activeProject={id:9,client_id:42};
contextApp.quickAddProjectTask('todo');
assert.equal(contextApp.modal.form.project_id,9);
assert.equal(contextApp.modal.form.client_id,42);
assert.equal(contextApp.fieldsFor('tasks').some(f=>['project_id','client_id','lead_id'].includes(f.key)),false);
contextApp.openModal(null,null,false,'tasks');
assert.equal(contextApp.fieldsFor('tasks').some(f=>f.key==='client_id'),true);
app.$nextTick=fn=>fn();app.recomputeVisibleCols=()=>{};app.boardColumns=3;app.setBoardColumns();
assert.equal(store.get('zen-board-columns'),'3');
app.contacts=[{first_name:'Anna',last_name:'Kowalska',client_id:1}];app.clientName=()=> 'BudMax';app.contactSearch='budmax';
assert.equal(app.filteredContacts.length,1);
console.log('OK: local calendar dates, event filters, custom stage choices, density persistence and contact search.');
(async()=>{
 const japp=sandbox.crmApp();
 japp.api=async path=>path.startsWith('/clients')?{clients:[{id:1,name:'Firma'}],pages:1}:path==='/contacts'?[{id:2,first_name:'Anna',last_name:'Nowak',phone:'555'}]:[];
 await japp.loadDirectory(); assert.equal(japp.directory.length,2); assert.equal(japp.searchDirectory('555',true)[0]._type,'contact');
 japp.journal={selected:{id:2,_type:'contact',phone:'555',email:'a@test.pl'},history:[],content:'Rozmowa',loading:false};
 japp.setJournalKind('call'); assert.equal(japp.journal.status,'answered'); assert.equal(japp.journal.address,'555');
 japp.setJournalKind('email'); assert.equal(japp.journal.status,'outgoing'); assert.equal(japp.journal.address,'a@test.pl');
 let payload; japp.api=async(path,options)=>{payload=JSON.parse(options.body);return {id:10,...payload};}; japp.notify=()=>{};
 await japp.saveJournal(); assert.equal(payload.entity_type,'contact'); assert.equal(payload.communication_status,'outgoing'); assert.equal(japp.journal.history.length,1); assert.equal(japp.journal.content,'');
 japp.journal.content='Zachowaj'; japp.api=async()=>{throw Error('Brak połączenia');}; await japp.saveJournal(); assert.equal(japp.journal.content,'Zachowaj'); assert.equal(japp.journal.error,'Brak połączenia');
 japp.journal.history=[{id:9,kind:'call',content:'Stara treść',communication_status:'answered',address:'555'}];
 japp.$nextTick=()=>{};
 japp.editJournalCall(japp.journal.history[0]);
 assert.equal(japp.journal.editingId,9);
 japp.journal.content='Nowa treść';
 japp.api=async(path,options)=>{assert.equal(path,'/comments/9');assert.equal(options.method,'PUT');return {id:9,kind:'call',content:JSON.parse(options.body).content};};
 await japp.saveJournal();
 assert.equal(japp.journal.history[0].content,'Nowa treść');
 console.log('OK: directory pagination shape, journal search, defaults, save payload and failure recovery.');
})().catch(e=>{console.error(e);process.exitCode=1;});

(async()=>{
 const teamApp=sandbox.crmApp();
 teamApp.openTeamModal();
 teamApp.teamModal.form.name='Wsparcie';
 let createCalls=0;
 let finishCreate;
 teamApp.api=(path,options)=>{
  if(path==='/teams'){
   createCalls++;
   return new Promise(resolve=>{finishCreate=()=>resolve({id:7,...JSON.parse(options.body),members:[]});});
  }
  if(path==='/users') throw Error('Odświeżenie niedostępne');
 };
 teamApp.notify=()=>{};
 const save=teamApp.saveTeamModal();
 await teamApp.saveTeamModal();
 assert.equal(createCalls,1);
 finishCreate();
 await save;
 assert.equal(teamApp.teams[0].name,'Wsparcie');
 assert.equal(teamApp.teamModal.open,false);
 assert.equal(teamApp.teamModal.error,'');
 assert.equal(teamApp.teamModal.saving,false);
 console.log('OK: team creation survives user refresh failure and prevents duplicate submissions.');
})().catch(e=>{console.error(e);process.exitCode=1;});

(async()=>{
 const callApp=sandbox.crmApp();
 callApp.smsCalls=[{id:4,note:''}];
 callApp.entityTelephony.calls=[{id:4,note:''}];
 callApp.entityTelephonyModal.calls=[{id:4,note:''}];
 callApp.openCallNote({id:4,note:''});
 callApp.callNoteModal.note='Ustalenia';
 callApp.api=async(path,options)=>{
  assert.equal(path,'/sms/calls/4/note');
  return {id:4,note:JSON.parse(options.body).note};
 };
 callApp.notify=()=>{};
 await callApp.saveCallNote();
 assert.equal(callApp.smsCalls[0].note,'Ustalenia');
 assert.equal(callApp.entityTelephony.calls[0].note,'Ustalenia');
 assert.equal(callApp.entityTelephonyModal.calls[0].note,'Ustalenia');
 assert.equal(callApp.callNoteModal.open,false);
 console.log('OK: call notes update all visible histories.');
})().catch(e=>{console.error(e);process.exitCode=1;});

// Locale coverage, untouched custom stages and per-user inbox state.
assert.deepEqual(Object.keys(sandbox.window.ZenLocales.pl).sort(),Object.keys(sandbox.window.ZenLocales.en).sort());
sandbox.window.ZenI18n.locale='en';
const english=sandbox.crmApp();
assert.equal(english.t('Powiadomienia'),'Notifications');
assert.equal(english.t('Unknown custom name'),'Unknown custom name');
english.customLeadStages=[{id:'new',label:'Nowy'},{id:'review',label:'Weryfikacja'}];
assert.equal(english.leadStages[0].label,'New');
assert.equal(english.leadStages[1].label,'Weryfikacja');
english.editStages();assert.equal(english.stageDraft[0].label,'Nowy');
english.user={id:1};english.notifications=[{id:'activity:1'},{id:'activity:2'}];
assert.equal(english.unreadNotifications,2);
english.markNotificationsRead(['activity:1']);assert.equal(english.unreadNotifications,1);
assert.equal(store.get('zen-notifications:1'),'["activity:1"]');
assert.equal(store.get('zen-notifications:2'),undefined);
english.notifications.push({id:'activity:3'});assert.equal(english.unreadNotifications,2);
english.markNotificationsRead();assert.equal(english.unreadNotifications,0);
sandbox.window.ZenI18n.locale='pl';
console.log('OK: locale parity, English labels, custom stage preservation and per-user notification read state.');

// Dashboard task tabs and formatting
assert.equal(app.dashboardTaskTab, 'today');
app.stats.overdue_tasks = [{ id: 10, title: 'Zadanie zaległe', due_date: '2026-09-01T10:00:00', priority: 'high' }];
app.stats.today_tasks = [{ id: 11, title: 'Zadanie na dziś', due_date: '2026-09-28T15:30:00', priority: 'medium' }];
app.stats.upcoming_tasks = [{ id: 12, title: 'Zadanie przyszłe', due_date: '2026-10-05T12:00:00', priority: 'low' }];
assert.equal(app.dashboardTasksByTab('overdue').length, 1);
assert.equal(app.dashboardTasksByTab('overdue')[0].id, 10);
assert.equal(app.dashboardTasksByTab('today').length, 1);
assert.equal(app.dashboardTasksByTab('today')[0].id, 11);
assert.equal(app.dashboardTasksByTab('upcoming').length, 1);
assert.equal(app.dashboardTasksByTab('upcoming')[0].id, 12);

// Date formatting in dashboard
assert.equal(app.formatTaskDate({ due_date: null }, 'upcoming'), 'Bez terminu');
assert.equal(app.formatTaskDate({ due_date: '2026-09-01T10:00:00' }, 'overdue'), '01.09.2026');
console.log('OK: dashboard task tabs partitioning and date formatting.');
