const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const sandbox = {window: {ZenI18n: {t: text => text}, location: {origin: 'http://localhost:5000'}}};
vm.createContext(sandbox);
for (const name of ['navigation', 'email']) vm.runInContext(fs.readFileSync(`frontend/js/settings/${name}.js`, 'utf8'), sandbox);
const editor = sandbox.window.ZenSettings.navigation();
editor.newClientStatusName = 'Stały klient';
editor.newClientStatusColor = '#123456';
editor.addClientStatus();
assert.equal(editor.clientStatusDraft[0].label, 'Stały klient');
assert.equal(editor.clientStatusDraft[0].id, 'staly_klient');
assert.equal(editor.clientStatusDraft[0].accent, '#123456');
editor.newClientStatusName = 'Stały klient';
editor.addClientStatus();
assert.notEqual(editor.clientStatusDraft[0].id, editor.clientStatusDraft[1].id);
for (const name of ['123 VIP', '客戶', 'Bardzo długa nazwa statusu klienta z polskimi znakami']) {
    editor.newClientStatusName = name;
    editor.addClientStatus();
    const status = editor.clientStatusDraft.at(-1);
    assert.equal(status.label, name);
    assert.match(status.id, /^[a-z][a-z0-9_]{0,19}$/);
}
const count = editor.clientStatusDraft.length;
editor.newClientStatusName = '   ';
editor.addClientStatus();
assert.equal(editor.clientStatusDraft.length, count);
assert.ok(editor.settingsError);
const id = editor.clientStatusDraft[0].id;
editor.clientStatusDraft[0].label = 'Zmieniona nazwa';
assert.equal(editor.clientStatusDraft[0].id, id);
const email = sandbox.window.ZenSettings.email();
email.selectedEmailTemplate = {variables: ['{{name}}', '{{email}}', '{{name}}', null]};
assert.deepEqual(Array.from(email.emailTemplateVariables()), ['{{name}}', '{{email}}']);
email.selectedEmailTemplate = {variables: '{{name}},{{email}}, '};
assert.deepEqual(Array.from(email.emailTemplateVariables()), ['{{name}}', '{{email}}']);
email.selectedEmailTemplate = {variables: 42};
assert.equal(email.emailTemplateVariables().length, 0);
email.settingsForm = {};
email.emailTemplateForm = {subject: 'Test', body_html: '<div>{{company_logo}}</div>'};
assert.ok(!email.getRenderedEmailPreview().html.includes('onerror='));
console.log('Status editor and email variable tests passed');
