"""offer/document render + pdf

Revision ID: 3ee44d0cd943
Revises: 1a4521a23b68
Create Date: 2026-09-24 19:07:01.097188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee44d0cd943'
down_revision = '1a4521a23b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rendered_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('pdf_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('public_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_public_token'), ['public_token'], unique=True)

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rendered_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('public_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('pdf_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_offers_public_token'), ['public_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_public_token'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('pdf_path')
        batch_op.drop_column('public_token')
        batch_op.drop_column('data')
        batch_op.drop_column('rendered_html')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_public_token'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('public_token')
        batch_op.drop_column('pdf_path')
        batch_op.drop_column('data')
        batch_op.drop_column('rendered_html')

    # ### end Alembic commands ###
